---
name: GoogleGeocoding
envs:
  GOOGLEAPIS_HOST: "@host"
  GEOCODING_KEY: "@key"
commands:

- name: Geocode
  input:
    address: "@address"
  request:
    type: GET
    path: "@host/maps/api/geocode/json?address=@address/&key=@key"



